version: "3.9"

services:
  redis:
    image: "redis:alpine"
    container_name: container-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - "./server:/redis:/data"


  web:
    build: .
    depends_on:
      - 'redis'
    image: kaneai/mango-server-bot
    container_name: container-server-bot
    restart: always
    env_file:
      - server/.env
    ports:
      - 80:80
    volumes:
      - ./server:/server

