version: "3.9"

services:
  redis:
    image: "redis:alpine"
    container_name: container-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - "./server:/redis:/data"

  app:
    build: server/
    depends_on:
      - 'redis'
    env_file:
      - server/.env
    image: kaneai/mango-server-bot
    container_name: container-server-bot
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./server:/server

