version: "3.9"

services:
  redis:
    image: "redis:alpine"
    container_name: container-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - "./server:/redis:/data"

  mongodb:
    image: mongo
    container_name: container-db
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - 27017:27017
    restart: always
    volumes:
      - ./db:/data/db

  app:
    build: .
    depends_on:
      - 'redis'
    image: kaneai/mango-server-bot
    container_name: container-server-bot
    restart: always
    ports:
      - 80:80
    volumes:
      - ./server:/server

