name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Heroku login Container
      env:
        HEROKU_USERNAME: ${{ secrets.HEROKU_USERNAME }}
        HEROKU_API_TOKEN: ${{ secrets.HEROKU_API_TOKEN }}
      run: |
        docker login --username=$HEROKU_USERNAME --password=$(heroku auth:$HEROKU_API_TOKEN) registry.heroku.com

    - name: Build the Docker image
      env:
        HEROKU_API_TOKEN: ${{ secrets.HEROKU_API_TOKEN }}
        PYTHONPATH: ${{ secrets.PYTHONPATH }}
        apiKey: ${{ secrets.APIKEY }}
        authDomain: ${{ secrets.AUTHDOMAIN }}
        databaseURL: ${{ secrets.DATABASEURL }}
        projectId: ${{ secrets.PROJECTID }}
        storageBucket: ${{ secrets.STORAGEBUCKET }}
        messagingSenderId: ${{ secrets.MESSAGINGSENDERID }}
        appId: ${{ secrets.APPID }}
        measurementId: ${{ secrets.MEASUREMENTID }}
        type: ${{ secrets.TYPE }}
        project_id: ${{ secrets.PROJECT_ID }}
        private_key_id: ${{ secrets.PRIVATE_KEY_ID }}
        private_key: ${{ secrets.PRIVATE_KEY }}
        client_email: ${{ secrets.CLIENT_EMAIL }}
        client_id: ${{ secrets.CLIENT_ID }}
        auth_uri: ${{ secrets.AUTH_URI }}
        token_uri: ${{ secrets.TOKEN_URI }}
        auth_provider_x509_cert_url: ${{ secrets.AUTH_PROVIDER_X509_CERT_URL }}
        client_x509_cert_url: ${{ secrets.CLIENT_X509_CERT_URL }}
        MONGODB_URI: ${{ secrets.MONGODB_URI }}
      run: |
        docker build . --file Dockerfile --tag my-image-name:$(date +%s)

      

